#!/bin/bash
# AYESEC:POST_SHS('173 lines')=92207d2112e91936ab440b0b66c6656027f5d2fb51f851c24259ab09782701cfb7b224a8de90d99beab3c2b9a33fb2361a4879f81103041fe57ab6a4e1435aed
# AYESEC:FILE_TOP('ayevdi/ost/ayevdi-sfrom-init')

# AYESEC:POST_SHS('26 lines')=c108bc8dce63695b1554023282d716f23813136ddbba66c941c6e9f3bc86e775cfeddd1fea5ab66d9f8316f37ae727f7810fa872452b63983878f16c0b5714d2
# AYESEC:MASTPOST_NOTICE
# AYESEC:POST_SHS('22 lines')=e9160e0b3075069c3a634cf1cccf76273426e72c86687d176f6bc33f33c3db2c53e6c793abc71a5a639adde8c14f2ebfc0f39da0874785106a43907d96448344
# AyeVDI
# Virtualized Deployment IaaS (VDI) by AyeAI
# 
# NOTICE
# Copyright (C) 2019-2020 Abhishek Choudhary, Dr Srija Katta
# 
# To all WHO IT MAY CONCERN,
# Greetings,
# All artifacts and methods in this project are offered with 
# NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only),
# subject to the jurisdictions of courts in Hyderabad, India,
# and solely in accordance with AyeAI SPL version 1, or later,
# as expressed at the follow URL and at the most current update
# https://raw.githubusercontent.com/ayeai/spl/master/LICENSE
# incuding its clauses of automatic implicit update of license,
# and unless in conflict the terms and conditions of GNU GPL v2
# shall apply with no retort to other GPL licenses, AND, These
# terms and conditions are implied read, understood and accepted
# by the access, or usage of these artifacts and methods which
# must STRICTLY be IN ACCORDANCE, and this notice must be 
# reproduced in derivatives along with the original assertions
# of copyrights and other rights reserved.
# AYESEC:PREV_SHS('22 lines')=e9160e0b3075069c3a634cf1cccf76273426e72c86687d176f6bc33f33c3db2c53e6c793abc71a5a639adde8c14f2ebfc0f39da0874785106a43907d96448344
# AYESEC:MASTPOST_NOTICE_COMPLETED
# AYESEC:PREV_SHS('26 lines')=c108bc8dce63695b1554023282d716f23813136ddbba66c941c6e9f3bc86e775cfeddd1fea5ab66d9f8316f37ae727f7810fa872452b63983878f16c0b5714d2

# AYESEC:POST_SHS('39 lines')=dfe7bded8bc5c9f15b58dae691ec611775d67b0d39e3daf370808ba6a680834c5595a03ed7d2debe1657d9a1f451831daf992d76b0da5d1fdee11eb19baa73a8
# AYESEC:ONE_FILE_EXCEPTION("ayevdi-sfrom-init")
# This is an exception header for ayevdi-sfrom-init as AyeVDI
# is not expected to have been initialized till this file is
# called. Hereafter, use the follwing sample in each script
# header. For other types of artifacts, please see URL below
# https://bit.ly/ayevdi-headers
# Sample bash statutory header:
#   To use see output of the command below (without #)
#   wget https://bit.ly/ayevdi-sfrom-init -O- -q | cut -c 2- | head -55 | tail -18
## AYESEC:POST_SHS('18 lines')=9e65a33c9f13130a71e5588e1211b9d2
## AYESEC:STATUTORY_HEADER
#if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
#then
#  echo "AyeVDI by https://ayeai.xyz"
#  echo "Copyright (C) 2019-2020 Abhishek Choudhary, Dr Srija Katta"
#  echo ""
#  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
#  echo "Further usage of these software, artifacts or methods"
#  echo "are subject to the 'latest' license agreement avaialble at"
#  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
#  echo ""
#  echo "AyeVDI not activated. Please use the following command to"
#  echo "activate AyeVDI"
#  echo '  ayesh=$(tempfile) && wget https://bit.ly/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
#  echo ""
#  exit
#fi
## AYESEC:STATUTORY_HEADER_COMPLETED
## AYESEC:PREV_SHS('18 lines')=9e65a33c9f13130a71e5588e1211b9d2

if [ ! -f ${HOME}/.ayevdi/ayevdi-sourcefrom ]
then
  mkdir -p ${HOME}/.ayevdi/
  wget https://bit.ly/ayevdi-sfrom -O- -q > ${HOME}/.ayevdi/ayevdi-sourcefrom
fi

export ayevdi_sourcefrom=${HOME}/.ayevdi/ayevdi-sourcefrom

# AYESEC:ONE_FILE_EXCEPTION_COMPLETED
# AYESEC:PREV_SHS('39 lines')=dfe7bded8bc5c9f15b58dae691ec611775d67b0d39e3daf370808ba6a680834c5595a03ed7d2debe1657d9a1f451831daf992d76b0da5d1fdee11eb19baa73a8

# AYESEC:POST_SHS('18 lines')=9da1fc9afc1b85e1e81e78a53f97d4436d886182eec170ddd6c78ec71e64113d9ade4fd1bf969ed5bbe62baed9a575d2b5e3ccdc0383c27eb7a4b6bc71965afe
# AYESEC:STATUTORY_HEADER
if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
then
  echo "AyeVDI by https://ayeai.xyz"
  echo "Copyright (C) 2019-2020 Abhishek Choudhary, Dr Srija Katta"
  echo ""
  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
  echo "Further usage of these software, artifacts or methods"
  echo "are subject to the 'latest' license agreement avaialble at"
  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
  echo ""
  echo "AyeVDI not activated. Please use the following command to"
  echo "activate AyeVDI"
  echo '  ayesh=$(tempfile) && wget https://bit.ly/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
  echo ""
  exit
fi
# AYESEC:STATUTORY_HEADER_COMPLETED
# AYESEC:PREV_SHS('18 lines')=9da1fc9afc1b85e1e81e78a53f97d4436d886182eec170ddd6c78ec71e64113d9ade4fd1bf969ed5bbe62baed9a575d2b5e3ccdc0383c27eb7a4b6bc71965afe

# AYEINTERNS:TASK:Automate generation of file level and section MD5 sum
# Suggestions: Use tags to autofill the lines covered and the md5 sum
# AYEINTERNS:TASK_END

# AYEINTERNS:TASK:Automate validation of file level and section MD5 sum
# Suggestions: Ensure correctness and validity of the vaidator itself!
# AYEINTERNS:TASK_END

# AYESEC:POST_SHS('28 lines')=a348aebd80d97f4147310b690f48f637d049130082479b76a2f57213175cf93f0b6ac5a8bd6bb8d32bd42b51bfbfade2b16738b7e3f105f6e203d12fbd67a377
# AYESEC_NOTICE:'The following 27 lines must not be modified or removed'
# AYESEC:POST_SHS('25 lines')=e040aa614314e690474747deeb3a5f6ca3a1cf5dc4e0ade5ae4ffa1170fc5d503faca0aa14e844ffd0bf3501fff638ae482c302819e63ea25985c49d53d757d3
# AYESEC:SIGNATURE_PLAINTEXT_SOURCEFROM
# Line 2
echo "Welocome to AyeVDI by https://ayeai.xyz"
echo "Copyright (C) 2019-2020 Abhishek Choudhary, Dr Srija Katta"
echo ""
# Line 6
echo "AyeVDI sourcefrom activated!"
echo ""
echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
echo "Further usage of these software, artifacts or methods"
echo "are subject to the 'latest' license agreement avaialble at"
echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
echo ""
# Line 14
echo "If you do not accept the above terms and conditions, you"
echo "may not use this software, and are at liberty to use the"
echo "following commands in a bash terminal to remove traces,"
echo "under the supervision of someone familiar with 'bash shell'"
echo "         rm -rf "'${HOME}'"/.ayevdi"
echo "         export ayevdi_sourcefrom=THANK YOU"
echo ""
echo "Towards greater glories with peace on Earth and beyond..."
echo ""
# Line 24
# AYESEC:SIGNATURE_PLAINTEXT_SOURCEFROM_COMPLETED
# AYESEC:PREV_SHS('25 lines')=e040aa614314e690474747deeb3a5f6ca3a1cf5dc4e0ade5ae4ffa1170fc5d503faca0aa14e844ffd0bf3501fff638ae482c302819e63ea25985c49d53d757d3
# AYESEC:PREV_SHS('28 lines')=a348aebd80d97f4147310b690f48f637d049130082479b76a2f57213175cf93f0b6ac5a8bd6bb8d32bd42b51bfbfade2b16738b7e3f105f6e203d12fbd67a377

# NOTICE: The use of aliases is convenient but exposes a potential
# man-in-the-middle threat

alias ayevdi-sourcefrom='. ${ayevdi_sourcefrom}'
alias sourcefrom='ayevdi-sourcefrom'

alias ayevdi-bsf='ayevdi-sourcefrom bsf'

alias ayevdi-validator='ayevdi-bsf https://bit.ly/ayevdi-validator'
alias validator='ayevdi-validator'

alias ayevdi-logger='ayevdi-bsf https://bit.ly/ayevdi-log'
alias logger='ayevdi-logger'

logger "AyeVDI sourcefrom activated... using ${ayesh}"

validator ${ayesh} >${HOME}/.ayevdi/ayevdi-validator.$(basename ${ayesh})

cat ${HOME}/.ayevdi/ayevdi-validator.$(basename ${ayesh}) | (if [ 0 -lt $(grep AYESEC:ERROR | wc -l) ];
  then
    logger "AYESEC:ERROR:Abort! Abort! Abort!"
    echo "WARNING: AyeVDI has detected an error, that may be a potential threat!"
    echo "Abort! Abort! Abort! Exiting shell in 10 secs... Press ctrl-c to stop abort..."
    sleep 10
    logger "Aborting on AYESEC:ERROR"
    echo "Aborting on AYESEC:ERROR"
    cp ${HOME}/.ayevdi/ayevdi-validator.$(basename ${ayesh}) ${HOME}/.ayevdi/ayevdi-error.fatal
  else
    logger "The Lion has roared!"
    echo ""
    sourcefrom https://bit.ly/ayevdi-mascot
  fi) && echo ""
  
if [ -e ${HOME}/.ayevdi/ayevdi-error.fatal ]
then
  #TBD: Decide whether to close shell here
  echo "WARNING: The shell may exit at this point in future versions"
fi

# AYESEC:FILE_END('ayevdi/ost/ayevdi-sfrom-init')
# AYESEC:PREV_SHS('173 lines')=92207d2112e91936ab440b0b66c6656027f5d2fb51f851c24259ab09782701cfb7b224a8de90d99beab3c2b9a33fb2361a4879f81103041fe57ab6a4e1435aed
